# Generated by Django 2.1.2 on 2018-12-06 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tienda',
            old_name='nombreSucursal',
            new_name='sucursal',
        ),
    ]
