# Generated by Django 2.1.2 on 2018-12-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181205_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('COMPRADO', 'Comprado'), ('VENDIDO', 'Vendido')], default='COMPRADO', max_length=30),
        ),
    ]
