# Generated by Django 2.1.2 on 2018-12-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_producto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('COMPRADO', 'Comprado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=30),
        ),
    ]
