# Generated by Django 2.1.2 on 2018-12-06 18:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_producto_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAgregados', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('totalComprados', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costoReal', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('costoPresupuestado', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Lista'),
        ),
    ]
