# Generated by Django 2.1.2 on 2018-12-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181206_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='nombre',
            field=models.CharField(default='lista1', max_length=30),
            preserve_default=False,
        ),
    ]
