# Generated by Django 2.1.2 on 2018-12-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_lista_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nombre',
            field=models.CharField(default='Lista 1', max_length=30),
        ),
    ]
