# Generated by Django 2.1.2 on 2018-12-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181206_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='lista',
        ),
    ]
