# Generated by Django 2.1.2 on 2018-12-06 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20181206_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Lista'),
        ),
    ]
