# Generated by Django 2.1.2 on 2018-12-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_detallecompra_precio_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='lista',
        ),
    ]
