# Generated by Django 2.1.2 on 2018-12-07 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20181206_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='compra',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Lista'),
        ),
    ]
