# Generated by Django 2.1.2 on 2018-12-07 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20181206_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='proveedor',
            new_name='lista',
        ),
    ]
