# Generated by Django 2.1.2 on 2018-12-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20181206_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='lista',
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Lista'),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
