# Generated by Django 2.1.2 on 2018-12-07 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20181206_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='lista',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='lista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Lista'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Tienda'),
        ),
        migrations.DeleteModel(
            name='DetalleCompra',
        ),
    ]
