# Generated by Django 2.1.2 on 2018-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20181207_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
