# Generated by Django 2.1.2 on 2018-12-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20181207_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=30),
        ),
    ]
