# Generated by Django 2.1.2 on 2018-12-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20181207_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(limit_choices_to={'estado': 'APROBADO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='est', to='blog.Tienda'),
        ),
    ]
